# Generated by Django 5.0.6 on 2024-06-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="is_client",),
    ]
